language: java
jdk:
# started to fail, replace by openjdk8  - oraclejdk8
  - openjdk8
  - oraclejdk11
# not available yet  - openjdk11

before_install:
 - chmod +x gradlew

#after_failure:
#- cat build/test-results/*.xml
